### ISSUE TITLE
Sidebar should stay up on fullscreen version

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#106]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

When the sidebar is expanded, it hides one of the banner panels at the top and some of the map, which is not ideal.

Can we fix this so that the sidebar shifts the banner & map over when expanded? Otherwise, you have to keep shrinking and expanding the sidebar which get to be a bit annoying. 

![Screen Shot 2020-04-08 at 10 59 50 PM](https://user-images.githubusercontent.com/58799043/78853563-30228480-79ed-11ea-86e9-bcbb245c2e70.png)

**Comment by KM-Hanson** [comment]
This would help solve issue #44 , at least for the fullscreen version.

**Comment by readingdancer** [comment]
@KM-Hanson - It does this on purpose and works in the same way Google Maps and other full screen mapping sites currently work.

I suggest that on screen sizes that are XL or above ( we use bootstrap and screens are divided into XS / S / M / L / XL ) we fix the left menu permanently to the left and completely remove the sliding effect. ( This might work from the Large size, I suggest whole does the development tries and sees which size works best )

For the smaller screen sizes, ( which would mainly be tablets or people who don't have their browser at full screen size ) the slide effect would still work.

@KM-Hanson - Does that work for you?

**Comment by KM-Hanson** [comment]
@readingdancer Fixing the sidebar where feasible seems like a good idea.

Another option would be to stack the 4 banner boxes as a square rather than have then in a line at the top of the page. The 4 panels would be in a 2x2 square at the top right of the map. Is that at all a workable solution?

**Comment by readingdancer** [comment]
As you know, this is what we do at the smaller size, I purposefully have not done that as I have been trying to limit the amount of vertical space we take away from the map. I think we should implement this as a first step and then perhaps look to improve things at other screen sizes if we still don't like the user experience.
