### ISSUE TITLE
Request to know user's location (as a way to center the map for the user & suggest nearby resources)

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#108]
****Have an idea for an additional feature?**
(a) Describe the feature**

Would it be possible to determine a user's location & then ask permission to use that location to adjust their experience?

**(b) How does it need to perform?**

If a user allows access to their location, then 
(1) the map could move to a centroid near that location as the default view
(1) resources could be sorted based on geographic proximity

(c) How will we code it?

**Describe alternatives you've considered**

**Additional context**

**Comment by readingdancer** [comment]
Yes this is possible, there are plugins for leafletjs that do this :)

**Comment by readingdancer** [comment]
@KM-Hanson - I created a new ticket to split this request into two distinct bits of functionality and have already implemented a solution to this new ticket, I will hopefully put it live tomorrow.

[Sort resources based on geographic proximity](https://github.com/code-for-chapel-hill/NC-COVID-Support/issues/178)

**Comment by cw2908** [comment]
Hi,

I can take this issue. I was able to find the solution.

**Comment by readingdancer** [comment]
This PR fixes this item:
https://github.com/code-for-chapel-hill/NC-COVID-Support/pull/224

It was mainly written by @cw2908 and then enhanced by @eparadise and editing by @readingdancer  , a great team effort :)

**Comment by readingdancer** [comment]
@all-contributors add @cw2908 to code
