### ISSUE TITLE
Add Data Privacy statement to the About Us panel

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#117]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

We should add a statement on data privacy/data use. Here is a working version that I added to the Google forms to submit and update information.

NOTE ON DATA SHARING
The information on NC COVID Support has been gathered from public web sources by volunteers or entered by business owners/resource providers. The data are provided to assist the public, local businesses, government partners, and non-profits during the COVID-19 pandemic. The data should not be used for commercial ventures or other purposes without the express permission of NC COVID Support.

**Comment by KM-Hanson** [comment]
Related to #116

**Comment by dsummersl** [comment]
It looks like someone with a licensed copy of BabelEdit would need to work on this ticket (to provide the other translations anyway...the demo version won't translate this text for me :( ).

**Comment by readingdancer** [comment]
If someone implements this functionality using the translation variables and then just tags me again in this ticket, I can do all the translations as I paid for a license of the BabelEdit software.

**Comment by eparadise** [comment]
I'll try working in it with translation variables!
