### ISSUE TITLE
Make the project indexable - follow CfA guidelines

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#118]
Excerpted from this page:
https://discourse.codeforamerica.org/t/making-your-project-contributor-friendly/737

(1) Add your brigade and projects list to the organizations.json file so that it shows up on the Brigade Project Index. ([Instructions are here](https://github.com/codeforamerica/brigade-information#how-to-add-or-edit-your-brigade-for-the-api)

(2) Add a description and URL in the title area at the top of the page on each of your repositories on Github.

(3) Add metadata files to your repository – for example, [publiccode.yml](https://docs.italia.it/italia/developers-italia/publiccodeyml-en/en/master/index.html) or [civic.json](https://github.com/BetaNYC/civic.json)

(4) Add tags to your Github repository. (You can find tags that map to topics on the [Brigade Project Index](https://statusboard.brigade.cloud/#/topics)) 

(5) Add links to Code for America and to your brigade’s website in the project’s README file.

**Comment by readingdancer** [comment]
I think this should all be done now, the changes have been merged into the CfA file and our projects are showing up on their site.
