### ISSUE TITLE
Create a CONTRIBUTING document

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#119]
Excerpt from 

https://discourse.codeforamerica.org/t/making-your-project-contributor-friendly/737

Create a CONTRIBUTING document
A CONTRIBUTING document is a starting point for many who would like to get involved in your project. A good one does the following things:

Starts with the problem and proposed solution, in just a couple of sentences.
Identifies the major workstreams involved in bringing the project to life.

Identifies the types of skills you need on the project, and what work streams they could contribute to. The idea here is to help a new volunteer easily see themselves successfully contributing to the project.

Provides points of contact for getting involved: links to project documentation, Slack or chat channels, code repositories, relevant websites or forms, etc.

Provides several sections of detailed information on how to contribute (as relevant to the project):

technical details about software development processes, tools and libraries used, getting setup to work on the project, expectations for automated testing, code style, and pull requests

human processes for data entry or conducting events related to the project

any relevant approval steps or processes

any relevant background, legal frameworks, or standards that must be met as a condition on success of the project

how meetings are conducted, and a schedule of regularly recurring meetings

contact information for a lead for each of the workstreams identified

Provides links to background resources, talks or presentations, articles and other materials about your project and its context.

Identifies contributors to your project. Consider using all-contributors on your project Github repository.

**Comment by readingdancer** [comment]
I have installed All Contributors ( https://allcontributors.org/ )

So here goes an initial test:

@all-contributors please add @readingdancer for code data doc design ideas platform review translation tutorial

**Comment by readingdancer** [comment]
@all-contributors please add @KM-Hanson for business content data doc ideas projectManagement question

**Comment by readingdancer** [comment]
This ticket is now done 👍
