### ISSUE TITLE
Include your brigade’s projects in the national CfA Project Index

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#120]
The [Project Index Statusboard](https://statusboard.brigade.cloud/#/) aggregates all Code for America brigade projects and displays them on a map. Adding your brigade’s projects to the Statusboard can be done through one of several automated (or semi-automated) processes.

See instructions at 
https://brigade.cloud/contributing/list-brigade-projects.html

**Comment by readingdancer** [comment]
@KM-Hanson  I have submitted a pull request for this, hopefully that's all we will need to do :)

https://github.com/readingdancer/brigade-information/pull/1

I will leave this ticket open until we know it's working :)

**Comment by readingdancer** [comment]
This has now been merged in and you can see our project info on their site. Unfortunately their map does not zoom in enough and it looks like Chapel Hill might be buried under other markers or is not being shown on the map at all. I will try and follow up with them about this tomorrow. 

https://statusboard.brigade.cloud/#/brigade/code-for-chapel-hill
