### ISSUE TITLE
Add info on how to contribute data or replicate the site to the Contribute.md file?

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#132]
The Contribute.md file as of 4/16/20 focuses on how to contribute to the code.

As such, I added a spreadsheet template for the database to the ReadMe file instead of to the Contribute.md file.

It seems like we should address how to contribute by (1) adding data or (2) replicating the site for another location outside of NC. 

@readingdancer Should we have separate "contribute" files for each? I don't want to overwhelm the current one.

**Comment by readingdancer** [comment]
@KM-Hanson 

Yes, I agree the data or content side of this project should be discussed in a separate document, the Contribute.md document should be purely related to how people can contribute to the software development side of the project.

We should also have a separate page of information about how to go about replicating the project.

**Comment by readingdancer** [comment]
@KM-Hanson - As discussed I have just added two additional files and at the same time I have moved all these files into the /docs folder.

I am sure you and I will both want to add more to these files over the next week, but at least this will give us a starting point.
