### ISSUE TITLE
Site not loading if www prefix used, possible DNS/CNAME issue

### ISSUE THREAD

**Issue by zhanknight** [code-for-chapel-hill/NC-COVID-Support#151]
**Describe the bug**
Site loads if accessed from https://nccovidsupport.org
Site does not load if accessed from https://www.nccovidsupport.org (DNS ERROR)

**Expected behavior**
Site should load either way - links in repo and twitter account point to the non-functional URL.

**Screenshots**
<img width="754" alt="Screen Shot 2020-04-19 at 3 39 54 PM" src="https://user-images.githubusercontent.com/20487008/79698062-56012200-8254-11ea-8ecf-43feb575372c.png">
<img width="754" alt="Screen Shot 2020-04-19 at 3 40 10 PM" src="https://user-images.githubusercontent.com/20487008/79698063-56012200-8254-11ea-880f-d3760ce985cf.png">

Possibly a CNAME issue with Github Pages? 
See here: https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by readingdancer** [comment]
@zhanknight - Thank you for submitting the issue, good spot!

To be honest I thought @garrisonreid and I had both tested this and it was working, so it's rather strange that it's not now.

I have just fixed the Twitter account to point to the correct domain, again, I was sure this was working... @KM-Hanson I don't suppose you changed this today? If not, it's a mystery :)

@garrisonreid would you have a chance to look at the DNS and the above help link?

Cheers,

Chris

**Comment by readingdancer** [comment]
@all-contributors please add @zhanknight for finding a bug

**Comment by readingdancer** [comment]
@garrisonreid has fixed this issue, thanks for submitting the issue @zhanknight 👍
