### ISSUE TITLE
Use a date format function on the last updated date when it is displayed.

### ISSUE THREAD

**Issue by readingdancer** [code-for-chapel-hill/NC-COVID-Support#184]
**Describe the bug**
I noticed on the Bay Area map that the last updated dates are currently showing in the following format: 2020-04-26T00:00:00Z

**To Reproduce**
1. Go to https://dcl-covid-19.github.io/mega-map-dev/
2. Click on Prepared Meals
3. Click on any listing
4. See error at the bottom of the listing details

**Expected behavior**
I think the date should just be shown as 04-26-2020

**Comment by readingdancer** [comment]
@mfincker I thought if you have time, you might like to fix this one in the core project and do a PR as I think it would be useful for others as well as your site :)

**Comment by pa2nther** [comment]
It looks like this is complete

**Comment by readingdancer** [comment]
It might be fixed on the Bay Area map, but no change has been sent back up to this repo so unfortunately it’s still a potential issue for others.
