### ISSUE TITLE
Add the ability to customize the header "logo"

### ISSUE THREAD

**Issue by readingdancer** [code-for-chapel-hill/NC-COVID-Support#193]
**Description of the new feature**

Currently the NC COVID Support branding is hard coded inside the [header.vue](https://github.com/code-for-chapel-hill/NC-COVID-Support/blob/master/covid-19-support/src/components/Header.vue) file. This should be pulled out so that it is easily customizable by other groups theming the site with their own branding.

**What we need to code**

The way I think this should probably be implemented in the current solution is by using [VueJS Slots](https://vuejs.org/v2/guide/components-slots.html) ideally each theme folder should be able to contain it's own components folder so that we can then dynamically pull in the appropriate component to pass in to this slot.

You will see one of the examples shows passing a component into the slot, you'll just need to figure out how to make this pull from the Theme > Components folder.

**Comment by eparadise** [comment]
@readingdancer are you working on this? I would be interested in looking into it if not!

**Comment by readingdancer** [comment]
Hi, yes I am working on this one, I "think" I've nearly finished it :)
