### ISSUE TITLE
Edit text on the "information" box to add Chatham County

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#207]
**What we need to code**
Edit the text in the information box shown below. The new text should read:

"Currently, this site supports Chatham County and Orange County, NC. With your help, we can expand our coverage."

Note - this box will likely go away in the redesign of the front end. But our partners in Chatham County are some of our best supporters at this point, so it is good to recognize them now.

![Screen Shot 2020-05-27 at 12 28 11 AM](https://user-images.githubusercontent.com/58799043/82977872-27900880-9fb1-11ea-920a-f7452b1cdcff.png)

**Comment by eparadise** [comment]
I can take this!

**Comment by eparadise** [comment]
Ah- my Babel trial has expired so I don't think I can change the text. @readingdancer maybe you can take care of it? Or anyone else with Babel.

**Comment by readingdancer** [comment]
@eparadise - If you can create a PR with the English Language change, I can then add the translations.
