### ISSUE TITLE
Edit text on partners on the "About us" page

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#208]
**What we need to code**
Edit the text shown under the "Info Sources" tab on the "About us" page.

(1) Remove the Carolina Farm Steward Association

(2) Add Pittsboro-Siler City Convention & Visitors Bureau linked to the following url:
https://visitpittsboro.com/

![Screen Shot 2020-05-27 at 12 30 51 AM](https://user-images.githubusercontent.com/58799043/82978148-dd5b5700-9fb1-11ea-9f03-3e5572a858c5.png)

**Comment by eparadise** [comment]
I can take this!
