### ISSUE TITLE
The Map Key needs a "Dark" theme applied.

### ISSUE THREAD

**Issue by readingdancer** [code-for-chapel-hill/NC-COVID-Support#211]
I think it is pretty clear from this screen grab, we need to apply the dark color theme to the Map Key.

![Map Key needs Dark Theme](https://user-images.githubusercontent.com/4398217/83155559-5d2b1380-a0cf-11ea-8d63-55509a784bfd.jpg)

I.e. It should have a grey background and the font should be light, in the same way as the language drop down.

**Comment by eparadise** [comment]
I can work on this!
