### ISSUE TITLE
Add social media links to the business details.

### ISSUE THREAD

**Issue by readingdancer** [code-for-chapel-hill/NC-COVID-Support#218]
**Description of the new feature**

The social media links should be added to the business details, the data is already available. These are optional, so the links should only be visible if we have their account details.

**What we need to code**

We have the following possible social media links in our data:

- Twitter
- Instagram
- Facebook.

**Comment by helenx15** [comment]
I'll take this one!

**Comment by readingdancer** [comment]
That's great, thank you @helenx15 

You should be able to use the Font Awesome icons and add these social media links underneath the current website link.

**Comment by helenx15** [comment]
#234

**Comment by readingdancer** [comment]
@all-contributors add helenx15 to code
