### ISSUE TITLE
Add the sites own social media links to the top navigation.

### ISSUE THREAD

**Issue by readingdancer** [code-for-chapel-hill/NC-COVID-Support#219]
**Description of the new functionality**

Using the Font Awesome icons for the social media platforms, we should add links into the header for the following:

- Facebook - https://www.facebook.com/nccovidsupport
- Twitter - https://twitter.com/nccovidsupport
- Instagram - https://instagram.com/nccovidsupport
- GitHub - https://github.com/code-for-chapel-hill/NC-COVID-Support

**Comment by ronitsingh1405** [comment]
I'm up for it!

**Comment by readingdancer** [comment]
Thanks, you will find Font Awesome is already used within the solution, so it should be pretty simple to use the appropriate icons. :)
