### ISSUE TITLE
Check to see if we already have permission to use the users location.

### ISSUE THREAD

**Issue by readingdancer** [code-for-chapel-hill/NC-COVID-Support#236]
**Description of the new feature**

When someone currently visits our site and they would like to turn on their location, they need to click the little location icon in the bottom right corner of the screen above the Zoom buttons.

When this is clicked, the user's browser requests the users confirmation and then stores that permission has been granted to use location on our site.

I think it should be possible to detect if we already have permission granted, when a user re-visits the site, we should immediately center the map on their current location and show the location circles.

**What we need to code**

- When re-visiting the website
- Check if we already have location permission
- Center the map on the user's current location

**Comment by joonyoungleeduke** [comment]
I'll try this!

**Comment by readingdancer** [comment]
Sorry @joonyoungleeduke - this one has already been done and is pending being merged in at the moment.
