### ISSUE TITLE
Problems with loading the site in Safari on Mac

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#239]
Version 9.1.2 (11601.7.7)

**Comment by KM-Hanson** [comment]
![Screen Shot 2020-06-23 at 12 49 12 AM](https://user-images.githubusercontent.com/58799043/85363695-892f8e00-b4ef-11ea-9dbf-3b6036c81127.png)

**Comment by readingdancer** [comment]
I think @KM-Hanson 's problem was that it was not showing the left hand section or the maps at all.

@eparadise - As you use a Mac, could you please check this ticket and chat with @KM-Hanson if you need more details?

**Comment by KM-Hanson** [comment]
No one else has been able to replicate this problem. It seems to be an issue with my computer. Closing the issue.
