### ISSUE TITLE
Add a "get directions" link out to Google Maps, to appear below the address

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#243]
@eparadise Leaving this to you :) The one trick here is we might only apply it to the map-based resources, and not the list-based resources.

**Comment by readingdancer** [comment]
We could do what the bay area have done and just link on the address, but this does not give you a proper link to the business on Google Maps. 

For this to work properly we need to add an additional field to our records that will allow us to link directly to the business, happy for this ticket to implement the address method, but I think we should aim for a better integration afterwards.

**Comment by readingdancer** [comment]
I suggest we add Google, Apple Maps and Waze

Here is the info for Waze: https://developers.google.com/waze/deeplinks

**Comment by KM-Hanson** [comment]
@readingdancer Can we start with just one re-direct to Google maps, and see how the user experience feels?

To make it work, can we start by redirecting to Google maps based on the lat/lon instead of the address? That might help avoid the navigation picking up the wrong business name, etc. We still might have mistakes, but that should help, yes?

Agreed that we can add better functionality for Phase 2.

**Comment by readingdancer** [comment]
For Google Maps, the most accurate way of doing this is to pass in the Place ID's as Waypoints:

```
https://www.google.com/maps/dir/?api=1&destination=Breakaway&destination_waypoint_id=ChIJJa59whfBrIkR7YQiZwLbbBU
```

We can find the place ID's by using the following page:

https://developers.google.com/places/place-id

This is not part of the scope of this ticket and is really a data entry task.

For now, I suggest we do the following request to navigation to a long / lat location:

https://www.google.com/maps/dir/?api=1&destination=35.784911,-79.0982256

**Comment by readingdancer** [comment]
Just to complete the set, the Apple Map instructions are here:

https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html

Now even if we don't implement them all, we can at least refer back to this ticket :)

**Comment by eparadise** [comment]
@readingdancer I implemented a get directions link for the meal mapper project, and I went by the address instead of the lat/long. I think that might be a better user experience because then at least when they see the pin in Google Maps they see the address it's directing to. What do you think?

**Comment by readingdancer** [comment]
@eparadise - As long as the coordinates are correct, when you do the search Google automatically puts the closest address into the search box.

**Comment by readingdancer** [comment]
Try this for example: 
https://www.google.com/maps/dir/?api=1&destination=35.8213371,-79.0866759

I just thought this would guarantee that we always linked to the right location, instead of Google potentially returning the wrong address if it didn't recognize it.

I don't mind either way, as long as it works. It will hopefully not be used for long, as I'd like us to use the Place ID's so we accurately link to the business.

**Comment by readingdancer** [comment]
For reference:
https://fontawesome.com/icons/google?style=brands
https://fontawesome.com/icons/waze?style=brands
https://fontawesome.com/icons/apple?style=brands
