### ISSUE TITLE
Improve the usability of the "show my location" icon.

### ISSUE THREAD

**Issue by readingdancer** [code-for-chapel-hill/NC-COVID-Support#248]
**Description of the new feature**

Currently the "show my location" icon looks like this:

![Current Show My Location Icon](https://user-images.githubusercontent.com/4398217/86034348-6c6fea80-ba08-11ea-9dfb-42a9962586eb.jpg)

#### First Version
At the moment this is the version that will be used, we would like the icon to be more prominent and touch friendly, so would like it to look like this:

![Your Location 1](https://user-images.githubusercontent.com/4398217/86034419-93c6b780-ba08-11ea-8d21-6d7cdb2e4dd8.jpg)

( It's like this on Google and Apple maps, so people will be familiar with it. )

#### Second Version

We would like a second CSS class created that will allow us to easily switch to a different layout that looks like the following:

![Your Location 2](https://user-images.githubusercontent.com/4398217/86034636-fc159900-ba08-11ea-8e20-986639efb33d.jpg)

Please note that the text must be normal HTML text as it will be translated.

### Write here as detailed as possible description about how this new feature should work

This must be implemented purely in CSS and use the Font Awesome Icon that we are currently using, we might change to a cross hair in the future, but this does not exist in the current free set of icons.

**Comment by aliciawu-dev** [comment]
i can try making this
