### ISSUE TITLE
Remove the “When do you need it” drop down

### ISSUE THREAD

**Issue by readingdancer** [code-for-chapel-hill/NC-COVID-Support#260]
**Description of the new functionality**
From our data it looks like this is not a very used feature and we would like to clean up the interface and remove it.

( we will be adding more filtering in the future )

**What we need to code**
Remove the drop down and re-code the VueJS code so that it does not try and filter by day of the week.

**Comment by a-rothwell** [comment]
#261

**Comment by readingdancer** [comment]
This has been completed by @a-rothwell thanks for your PR :)

**Comment by readingdancer** [comment]
@all-contributors add a-rothwell to Code
