### ISSUE TITLE
Add `rapid-response` topic tag

### ISSUE THREAD

**Issue by tdooner** [code-for-chapel-hill/NC-COVID-Support#285]
Hello NC Covid Support team!

I'm Tom, an engineer at Code for America and part of the team of Brigade Network members [working to index projects](https://discourse.codeforamerica.org/t/creating-a-brigade-wide-project-index-brigade-congress-2019/639) in a way that improves discoverability of projects that are aligned with the Priority Action Areas of the network.

Since this project is featured in the [Rapid Response Priority Action Area](http://brigade.codeforamerica.org/priority-action-areas/rapid-response), we'd love to have it indexed in this effort as well. You can accomplish this by adding this additional tag to this repository:

* `rapid-response`

You may want to add other tags as well, to represent technologies in use, the format of the project, or any other affiliations. [Here is a great example](https://github.com/hackforla/food-oasis) of a repository tagged for increased discoverability.

One more thing! While you're updating the repository, you may want to check that the repo's description and web URL are up-to-date. We will use those fields to send interested people to the right place.

Thanks! Let me know if you have any questions about this!

**Comment by readingdancer** [comment]
Hi @tdooner I have added the "rapid-response" tag, I think everything else is up to date, thanks :)
