### ISSUE TITLE
Use SMS to collect updates from & communicate with businesses using Twillo

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#41]
**Have an idea for an additional feature?**
(a) Describe the feature

It would be great to have a way to message businesses in our database and prompt them to update us if any of their information has changed. Through Code for America, we have access to free/discounted service through Twillo. 

Twillo is already being used for lots of COVID-19 projects! They have an [entire COVID page](https://www.twilio.org/customer/covid19/) and links to projects that walk you step-by-step how to set up work flows to send/receive info via SMS:

[How we built a COVID-19 volunteer support line for our local community using Twilio Studio](https://www.twilio.com/blog/covid-19-volunteer-support-line-twilio-studio)

[Build a SMS Chatbot With Python, Flask and Twilio](url)

**Comment by readingdancer** [comment]
This now has it's own GitHub project and has essentially been completed, as the development is separate from the main project I am closing this ticket to avoid any confusion.
