### ISSUE TITLE
Add information on which resource type is being mapped

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#44]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

The option to shrink the side bar to the right of the page is great, but it does cause one issue. When the side bar is hidden, the user can't tell which resource category is being mapped (restaurant? pharmacy? etc.) And some of the resources have the same banner categories, which makes it more confusing.

Can we find a way to add text near the title bar ("COVID-19 Community Resources) to indicate which resource category is being mapped?

![Screen Shot 2020-03-28 at 11 51 35 PM](https://user-images.githubusercontent.com/58799043/77839886-152f5500-714f-11ea-8906-6087643b931e.png)

**Comment by readingdancer** [comment]
@KM-Hanson We did chat about this, but I just thought I'd update the ticket :)

IMHO this does not matter, if the end user cannot remember what they searched for, it's unlikely they can use the website at all. Google Maps works in the same way, I think we can assume that if you searched for something, you will know and don't need to be reminded :)

Just my 2 UK pence...

Please close the ticket if you agree, or send me a reply :)

**Comment by suddengenesis** [comment]
It may still be useful to have a thin header above the buttons in case someone takes a screenshot to share with others, for instance. It might looks something like this: 
<img width="1240" alt="Screen Shot 2020-04-04 at 3 01 35 PM" src="https://user-images.githubusercontent.com/24510849/78459176-37f8c680-7685-11ea-94c6-8206c5d47a2d.png">

**Comment by KM-Hanson** [comment]
@readingdancer I think the thin header is a nice option. Maybe in a more noticeable color?

**Comment by suddengenesis** [comment]
Here's two other possible options- first one is the average of the two value box colors (5ba68f). I think it's a little busy and may clash. Second is purple tone (7777aa) that looks a little better to my untrained eye.
<img width="1239" alt="Screen Shot 2020-04-04 at 4 27 18 PM" src="https://user-images.githubusercontent.com/24510849/78460825-2c5fcc80-7692-11ea-996d-f273efaaf589.png">
<img width="1239" alt="Screen Shot 2020-04-04 at 4 28 14 PM" src="https://user-images.githubusercontent.com/24510849/78460827-2f5abd00-7692-11ea-8938-47ba845b416a.png">

**Comment by readingdancer** [comment]
We have discussed adding labels to the markers and on searches that return multiple types of businesses, show icons in the markers to help identify the business types.

@KM-Hanson - I think we should close this ticket and create two separate tickets for these two additions, is that ok for you?

**Comment by KM-Hanson** [comment]
@readingdancer Good idea! Thanks.

**Comment by readingdancer** [comment]
I have created issues #147 & #148 to replace this ticket.
