### ISSUE TITLE
Add open source license info on GitHub

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#52]
**Have an idea for an additional feature?**
(a) Describe the feature

We need to decide on and communicate the license for our site.

I don't have experience with this. Some info below. @garrisonreid Any CfA protocols here?

https://opensource.org/faq#which-license

**Comment by suddengenesis** [comment]
I've often seen places use Creative Commons: https://creativecommons.org/

Common derivations are here: https://creativecommons.org/share-your-work/licensing-examples/

**Comment by KM-Hanson** [comment]
Sounds like we should aim for CC BY-NC or CC BY-NC-SA.

Here is a summary from [Foter.com](https://foter.com/blog/how-to-attribute-creative-commons-photos/):

![Screen Shot 2020-03-29 at 10 20 55 PM](https://user-images.githubusercontent.com/58799043/77869180-96e4b880-720b-11ea-91d1-0b0c7053e3fa.png)

**Comment by suddengenesis** [comment]
I think you're right, @KM-Hanson. Either of those could work. Who can make the final call on this?

**Comment by KM-Hanson** [comment]
@suddengenesis I think CC BY-NC-SA is most appropriate.

Here is the link to the license language: (I have not yet read thoroughly! Not sure if we need to change any text)
https://creativecommons.org/licenses/by-nc-sa/2.0/legalcode

I think we should add:
(1) Copyright 2020 Code for Chapel Hill (scroll down on [this site](https://codefordurham.com/project/drivers-license-recovery/) for an example)

![Screen Shot 2020-04-05 at 12 18 28 AM](https://user-images.githubusercontent.com/58799043/78466757-3b1aa380-76d3-11ea-93c4-4f6ba08a073c.png)

(2) an image of the license logo....

The license logo is available for download either as the components or as an svg file from this page:
https://creativecommons.org/about/downloads


![Screen Shot 2020-04-05 at 12 15 20 AM](https://user-images.githubusercontent.com/58799043/78466732-ae6fe580-76d2-11ea-9d6f-63d8b1511563.png)

**Comment by KM-Hanson** [comment]
Opening a new Issue for adding the copyright and license logo.

**Comment by readingdancer** [comment]
Hi @KM-Hanson can we have a chat about this one on Monday so that I can put something up onto GitHub, let me know when you are free via Slack.

**Comment by readingdancer** [comment]
If you look on the Creative Commons website you will see that they [advise against using their licenses for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

I have added the following GPL v3 license to the project as I think it covers what we last discussed:

https://github.com/code-for-chapel-hill/NC-COVID-Support/blob/master/LICENSE
