### ISSUE TITLE
Add support for multiple phone numbers (ex: 2 different languages)

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/NC-COVID-Support#77]
**Have an idea for an additional feature?**
(a) Describe the feature

Can we add support for a resource that gives 2 contact phone numbers. For example....

English: 919.695.6334
Espanol: 919.698.8666

**Comment by readingdancer** [comment]
I think we should just add another column in the table for a Spanish phone number, then we simply display it if available. The label should be translated so shouldn't be in the text.

**Comment by readingdancer** [comment]
@KM-Hanson I have just added a new column: "contact_spanish" to the spreadsheet.

@fredlawl - If you do take on this ticket, you will find that the column will be called "contactspanish" as it removes the underscores.

**Comment by readingdancer** [comment]
Thanks to @dsummersl for adding a PR to implement this feature. 

@KM-Hanson - It's now been put live, however I don't yet see a single record with a Spanish number?

Also I can see some issues with the data in the Contact column, there should only ever be ONE number in that column, if you add more than one number in, you will break the call functionality on mobile.

**Comment by KM-Hanson** [comment]
@readingdancer Problematic phone #s are now fixed. We will have Spanish phone numbers coming for some of the community resources. I'll check to see if the school meal programs have Spanish contact info.
